# Addition and Subtraction Operations

## Import

In [3]:
import numpy as np

## Create Matrices

In [7]:
m = np.array([[2,3,4],[6,7,8]])

In [5]:
n = np.array([[64,55,47],[11,34,23]])

## Addition of matrices

In [6]:
m + n

array([[66, 58, 51],
       [17, 41, 31]])

## Subtract Matrices

In [8]:
n - m

array([[62, 52, 43],
       [ 5, 27, 15]])

In [9]:
m - n

array([[-62, -52, -43],
       [ -5, -27, -15]])

## Vectors

In [13]:
v1 = np.array([3,7,11])

In [18]:
v2 = np.array([19,15,-11])

## Vector Addition

In [16]:
v1 + v2

array([22, 22,  0])

## Vector Difference

In [17]:
v1 - v2

array([-16,  -8,  22])