# Imports

In [2]:
import numpy as np

# Scalars

In [3]:
s = 5

In [4]:
s

5

# Vectors

In [9]:
v = np.array([2,6,9])

In [10]:
v

array([2, 6, 9])

# Matrices

In [12]:
m = np.array([[2,4,-5],[3,-6,7]])

In [13]:
m

array([[ 2,  4, -5],
       [ 3, -6,  7]])

# Data Types

In [14]:
type(s)

int

In [15]:
type(v)

numpy.ndarray

In [16]:
type(m)

numpy.ndarray

In [17]:
s_array = np.array(s)

In [18]:
s_array

array(5)

In [19]:
type(s_array)

numpy.ndarray

# Data Shapes

In [21]:
m.shape

(2, 3)

In [22]:
v.shape

(3,)

In [29]:
# Get an error, s is a scalar with no shape
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [24]:
s_array.shape

()

# Making column vectors

In [26]:
m.reshape(3,2)

array([[ 2,  4],
       [-5,  3],
       [-6,  7]])

In [27]:
v.reshape(3,1)

array([[2],
       [6],
       [9]])

In [28]:
v.reshape(1,3)

array([[2, 6, 9]])