# Scalars

## Imports

In [1]:
import numpy as np

## Addition of scalars

In [2]:
5 + 20

25

In [3]:
5-5

0

## Matrices

In [4]:
m = np.array([[2,3,4],[6,7,8]])

In [5]:
n = np.array([[6,8],[4,-9]])

In [6]:
m + n

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [7]:
m - n 

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

## Vectors

In [8]:
v1 = np.array([10,20,30])

In [9]:
v2 = np.array([14,-67])

In [10]:
v1 + v2

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [11]:
v1 - v2

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## Exceptions(Addition with Scalars)

### Matrices and Scalars

In [15]:
m - 9

array([[-7, -6, -5],
       [-3, -2, -1]])

In [16]:
m + 2

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [20]:
n + np.array([-12])

array([[ -6,  -4],
       [ -8, -21]])

## Vectors and Scalars

In [17]:
v1 + 2

array([12, 22, 32])

In [18]:
v2 - 3

array([ 11, -70])

In [19]:
v2 + np.array([-10])

array([  4, -77])