# Creating Tensors

# Imports

In [1]:
import numpy as np

# Create matrices

In [2]:
m = np.array([[2,3,4],[6,7,8]])
m

array([[2, 3, 4],
       [6, 7, 8]])

In [3]:
n = np.array([[64,55,47],[11,34,23]])
n

array([[64, 55, 47],
       [11, 34, 23]])

# Create a tensor from the matrices

In [4]:
t = np.array([m,n])

In [5]:
t

array([[[ 2,  3,  4],
        [ 6,  7,  8]],

       [[64, 55, 47],
        [11, 34, 23]]])

# Shape of the Tensor

In [6]:
t.shape

(2, 2, 3)

# Creating a Tensor Manually

In [7]:
t1 = np.array([[[2,4,6],[9,6,3]],[[67,68,69],[70,71,72]]])

In [8]:
t1

array([[[ 2,  4,  6],
        [ 9,  6,  3]],

       [[67, 68, 69],
        [70, 71, 72]]])

In [9]:
t1.shape

(2, 2, 3)