# Transposing

In [1]:
import numpy as np

## Matrices

In [3]:
m = np.array([[2,3,4],[6,7,8]])
m

array([[2, 3, 4],
       [6, 7, 8]])

In [4]:
m.T

array([[2, 6],
       [3, 7],
       [4, 8]])

## Vectors

In [5]:
v = np.array([2,3,4,5])
v

array([2, 3, 4, 5])

In [11]:
v_reshaped = v.reshape(4,1)
v_reshaped

array([[2],
       [3],
       [4],
       [5]])

In [12]:
v_reshaped.T

array([[2, 3, 4, 5]])

## Scalars

In [14]:
s = np.array([9])
s

array([9])

In [15]:
s.T

array([9])