## Numpy Continuation

### Array Operations

In [1]:
import numpy as np

In [2]:
arr_1 = np.array([[5,6,8], [9,12,16], [-7,-10,-13]])

In [5]:
arr_2 = np.ones(3, dtype=int)

#### Addition

In [6]:
arr_1 + arr_2

array([[  6,   7,   9],
       [ 10,  13,  17],
       [ -6,  -9, -12]])

#### Subtraction

In [7]:
arr_1 - arr_2

array([[  4,   5,   7],
       [  8,  11,  15],
       [ -8, -11, -14]])

#### Multiplication

In [8]:
arr_3 = np.array([0,10,20])

In [9]:
arr_1 * arr_3

array([[   0,   60,  160],
       [   0,  120,  320],
       [   0, -100, -260]])

#### Division

In [11]:
arr_4 = np.array([10,20,30])

In [12]:
arr_1 / arr_4

array([[ 0.5       ,  0.3       ,  0.26666667],
       [ 0.9       ,  0.6       ,  0.53333333],
       [-0.7       , -0.5       , -0.43333333]])

`sum()` is used to find the sum of the elements in the array.

In [13]:
arr_4.sum()

np.int64(60)

To add rows or columns in a nD array, you would specify the axis.

You can sum the elemets over rows with

In [16]:
arr_1.sum(axis=0)

array([ 7,  8, 11])

Sum elements over columns with

In [17]:
arr_1.sum(axis=1)

array([ 19,  37, -30])

#### Broadcasting

Broadcasting is simply an operation between an _array_ and a _single number_ or operations between arrays of different sizes. Also, an operation between a _vector_ and a _scalar_.
Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes

In [19]:
arr_1

array([[  5,   6,   8],
       [  9,  12,  16],
       [ -7, -10, -13]])

In [20]:
arr_1 * -10

array([[ -50,  -60,  -80],
       [ -90, -120, -160],
       [  70,  100,  130]])

In [24]:
arr_5 = np.array([2,4,6])

In [25]:
arr_1 * arr_5

array([[ 10,  24,  48],
       [ 18,  48,  96],
       [-14, -40, -78]])

The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you will get a `ValueError`.

#### Mean
`mean` is used to find the mean of the elements in an array.

In [34]:
avg_arr = np.array([[10,24,48],
                    [18,48,96],
                    [-14,-40,-78]])

In [35]:
avg_arr.mean()

np.float64(12.444444444444445)

You can specify the _axis_ on which you want to find the mean.

In [36]:
avg_arr.mean(axis=0)

# Mean over the rows

array([ 4.66666667, 10.66666667, 22.        ])

In [37]:
avg_arr.mean(axis=1)

# Mean over the columns

array([ 27.33333333,  54.        , -44.        ])

#### Product

`prod` is used to get the result of multiplying the elements together

In [38]:
prod_arr = np.array([[10,24,48],
                    [18,48,96],
                    [-14,-40,-78]])

In [39]:
prod_arr.prod()

np.int64(-41736889958400)

In [42]:
prod_arr.prod(axis=0) # Row Products

array([  -2520,  -46080, -359424])

In [43]:
prod_arr.prod(axis=1) # Column Products

array([ 11520,  82944, -43680])

#### Maximum

`max` is used to find the maximum element in the array.

In [44]:
prod_arr

array([[ 10,  24,  48],
       [ 18,  48,  96],
       [-14, -40, -78]])

In [45]:
prod_arr.max()

np.int64(96)

In [46]:
prod_arr.max(axis=0)

array([18, 48, 96])

In [47]:
prod_arr.max(axis=1)

array([ 48,  96, -14])

#### Minimum
`min` method is used to find the minimum value in the array. You can set the axis to find the minimum valu per axis.

In [48]:
prod_arr

array([[ 10,  24,  48],
       [ 18,  48,  96],
       [-14, -40, -78]])

In [49]:
prod_arr.min()

np.int64(-78)

#### Standard Deviation
`std` method is used to find the standard deviation of the array. You can aggrgate the values by specicifing per axis.

In [52]:
prod_arr

array([[ 10,  24,  48],
       [ 18,  48,  96],
       [-14, -40, -78]])

In [53]:
prod_arr.std()

np.float64(48.66007058293075)

In [54]:
prod_arr.std(axis=0)

array([13.59738537, 37.14236874, 73.37574531])

In [55]:
prod_arr.std(axis=1)

array([15.69146973, 32.12475681, 26.28053779])