# Matrices

### Creating Matrices

In [2]:
import numpy as np

You can pass Python lists of lists to create an nD array or _Matrix_ to represent them in Numpy.

In [3]:
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [4]:
matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

You can perform all operations of the arrays on matrices.

In [5]:
matrix.min()

np.int64(10)

In [7]:
matrix.prod(axis=0)

array([ 28000,  80000, 162000])

In [8]:
matrix.mean(axis=1)

array([20., 50., 80.])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

(3, 3)

Slicing is also important while working with matrices.

In [11]:
matrix[0]

array([10, 20, 30])

In [12]:
matrix[0,2]

np.int64(30)

In [13]:
matrix[0:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [15]:
matrix[1:3]

array([[40, 50, 60],
       [70, 80, 90]])

Be aware that when NumPy prints N-dimensional arrays, the last axis is looped over the fastest while the first axis is the slowest. For instance:

In [17]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

 `random.Generator` class for random number generation for that. All you need to do is pass in the number of elements you want it to generate:

In [18]:
rng = np.random.default_rng()

In [19]:
rng.random(10)

array([0.28708447, 0.18442697, 0.42137412, 0.56068461, 0.14768961,
       0.84691404, 0.73023813, 0.41934624, 0.3952631 , 0.17641139])

You can also use `ones()`, `zeros()`, and `random()` to create a 2D array if you give them a tuple describing the dimensions of the matrix:

In [21]:
rng.random((3,2))

array([[0.20020451, 0.73679753],
       [0.73005858, 0.71814177],
       [0.50606587, 0.16540853]])

### Random Number Generation
The use of random number generation is an important part of the configuration and evaluation of many numerical and machine learning algorithms. 
Whether you need to randomly initialize weights in an artificial neural network, split data into random sets, or randomly shuffle your dataset, 
being able to generate random numbers (actually, repeatable pseudo-random numbers) is essential.

With `Generator.integers`, you can generate random integers from low (remember that this is inclusive with NumPy) to high (exclusive). 
You can set `endpoint=True` to make the high number inclusive.

You can generate a 2 x 4 array of random integers between 0 and 4 with:

In [26]:
rng.integer(5, size=(3,4))

AttributeError: 'numpy.random._generator.Generator' object has no attribute 'integer'

### Getting Unique Items and Counts

`np.unique()` helps find unique elements in an array easily. 

In [27]:
unq_arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [28]:
np.unique(unq_arr)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

`return_index` argument in `np.unique()` is used to get the indices of your unique elements in the array.

In [34]:
unique_values, indices_list = np.unique(unq_arr, return_index=True)

In [35]:
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [36]:
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


`return_counts` argument in `np.unique()` is used to return the frequency count of th unique values.

In [40]:
unique_values, count = np.unique(unq_arr, return_counts=True)

In [45]:
print(count)

[3 2 2 2 1 1 1 1 1 1]


### Transposing and Reshaping a Matrix

`arr.reshape()`, `arr.transpose()`, `arr.T`

In [46]:
matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

`reshape` is important when you want to switch the dimensions of your matrix. This is essential where you have a model that expects a certain shape of input that is different from your Dataset.

In [47]:
matrix.reshape(9,1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

`.transpose()` is used to reverse or change the axes of an array according to the values you specify.

In [48]:
matrix.transpose()

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

NumPy arrays have the property `T` that allows you to transpose a matrix

In [49]:
matrix.T

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

### Reversing an Array

`np.flip()` function allows you to flip, or reverse, the contents of an array along an axis. If you don’t specify the axis, NumPy will reverse the contents along all of the axes of your input array

In [55]:
flip_1d = np.array([1,2,3])  # 1D Array

In [56]:
np.flip(flip_1d)

array([3, 2, 1])

In [57]:
flip_2d = np.array([[45,35,67], [56,90,112]])  # 2D Array

In [58]:
np.flip(flip_2d)

array([[112,  90,  56],
       [ 67,  35,  45]])

You can reverse only the _rows_.

In [61]:
flip_2d

array([[ 45,  35,  67],
       [ 56,  90, 112]])

In [62]:
np.flip(flip_2d, axis=0)

array([[ 56,  90, 112],
       [ 45,  35,  67]])

only the _columns_

In [63]:
np.flip(flip_2d, axis=1)

array([[ 67,  35,  45],
       [112,  90,  56]])

You can also reverse the contents of only one column or row. For example, you can reverse the contents of the row at index position 1 (the second row):

In [64]:
np.flip(flip_2d[1])

array([112,  90,  56])

You can also reverse the column at index position 1 (the second column):

In [66]:
np.flip(flip_2d[:,1])

array([90, 35])

### Flattening and Reshaping Multi-Dimensional Arrays

`.flatten()`, `.ravel()`

The primary difference between the two is that the new array created using `ravel()` is actually a reference to the parent array (i.e., a “view”)

In [67]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [70]:
# When you flaten, changes to the new array do not reflect on the original array.
y = x.flatten()

In [74]:
y[0] = 13
y

array([13,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
# If you ravel the changes you make to your new array affects the original array.
q = x.ravel()

In [77]:
q

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [78]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
q[0] = 13

In [80]:
q

array([13,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [81]:
x

array([[13,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Finding Help
`help`, `?`, `??`

In [82]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more positional arguments, return the largest argument.



In [83]:
max?

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more positional arguments, return the largest argument.
Type:      builtin_function_or_method

In [84]:
max??

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more positional arguments, return the largest argument.
Type:      builtin_function_or_method

In [87]:
 # Our own array that we defined
q??

Type:        ndarray
String form: [13  2  3  4  5  6  7  8  9 10 11 12]
Length:      12
File:        c:\users\makot\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type,

`??` if used it allows you to access the source code which is another level of access.