# Saving and Loading Numpy Projects

`np.save`, `np.savez`, `np.savetxt`, `np.load`, `np.loadtxt`

This helps us save our arrays to disk and later load then later without re-running the full code.

`np.loadtxt` and `np.savetxt'` are used to save and load ndarray from disk files; normal text files.

`np.load` and `np.save` are used to handle Numpy binary files wi the `.npy` extension.

`np.savez` function that handles NumPy files with a `.npz` file extension.

`.npy` and `.npz` files store data, shape, dtype, and other information required to reconstruct the ndarray in a way that allows the array to be correctly retrieved, even when the file is on another machine with different architecture.

If you want to store a single ndarray object, store it as a `.npy` file using `np.save`.

If you want to store more than one ndarray object in a single file, save it as a `.npz` file using `np.savez`. 

You can also save several arrays into a single file in compressed npz format with `savez_compressed`.

It is easier to save and load an array using `np.save`. Only you have to ensure that you specify the array you want to save and the file name. Example:

In [2]:
import numpy as np

In [4]:
sav_arr = np.array([[10,20,30],[60,70,90]])

In [6]:
np.save('sav_array', sav_arr)

In [7]:
# Load 
b = np.load('sav_array.npy')

In [8]:
print(b)

[[10 20 30]
 [60 70 90]]


Use `np.savetxt` to save as a plain text file like `.csv` and `.txt`

In [9]:
np.savetxt('save_array_text.txt', sav_arr)

In [10]:
# Load you text file
a = np.loadtxt('save_array_text.txt')

In [11]:
print(a)

[[10. 20. 30.]
 [60. 70. 90.]]


The `savetxt()` and `loadtxt()` functions accept additional optional parameters such as _header_, _footer_, and _delimiter_. While text files can be easier for sharing, `.npy` and `.npz` files are smaller and faster to read.